name: etf_oglasi
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  http: ^1.3.0
  intl: ^0.19.0
  file_picker: ^10.1.2
  path: ^1.9.1
  open_filex: ^4.7.0
  permission_handler: ^12.0.0+1
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  flutter_riverpod: ^2.6.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0

flutter:
  generate: true

  uses-material-design: true

flutter_intl:
  enabled: true